In [3]:
# GRADED FUNCTION: normalizeRows

def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).

    Argument:
    x -- A numpy matrix of shape (n, m)

    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """

    ### START CODE HERE ### (≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    x_norm = np.linalg.norm(x, axis=1, keepdims = True);
    
    # Divide x by its norm.
    x = x / x_norm;
    ### END CODE HERE ###

    return x;
import numpy as np;
x = np.array([
    [0, 3, 4],
    [9, 0, 16]])
print(x);
print(normalizeRows(x));

[[ 0  3  4]
 [ 9  0 16]]
[[0.         0.6        0.8       ]
 [0.49026124 0.         0.87157554]]
